#!/bin/bash

# This script is used to check if a new computer has all the desired programs
# installed, if not it helps instruct how to install them.

# check for brew
if [[ ! $(command -v "brew") ]]; then
  echo -e "brew not installed. go to https://brew.sh/"
else
  echo -e "brew installed."
fi

# check for stow
if [[ ! $(command -v "stow") ]]; then
  echo -e "stow not installed. run brew install stow"
else
  echo -e "stow installed."
fi

# check for eza
if [[ ! $(command -v "eza") ]]; then
  echo -e "eza not installed. run brew install eza"
else
  echo -e "eza installed."
fi

# check for zoxide
if [[ ! $(command -v "zoxide") ]]; then
  echo -e "zoxide not installed. run brew install zoxide"
else
  echo -e "zoxide installed."
fi

# check for fzf
if [[ ! $(command -v "fzf") ]]; then
  echo -e "fzf not installed. run brew install fzf"
else
  echo -e "fzf installed."
fi

# check for fast node manager (fnm)
if [[ ! $(command -v "fnm") ]]; then
  echo -e "fnm not installed. run brew install fnm"
else
  echo -e "fnm installed."
fi
# check for node (and npm)
if [[ ! $(command -v "node") ]]; then
  echo -e "node not installed. run fnm install <VERSION>"
else
  echo -e "node installed."
fi

# check for neovim
if [[ ! $(command -v "nvim") ]]; then
  echo -e "neovim not installed. run brew install neovim"
else
  echo -e "neovim installed."
fi

# check for tmux
if [[ ! $(command -v "tmux") ]]; then
  echo -e "tmux not installed. run: brew install tmux"
else
  echo -e "tmux installed."
fi

# check for efm-langserver
if [[ ! $(command -v "efm-langserver") ]]; then
  echo -e "efm-langserver not installed. run: brew install efm-langserver"
else
  echo -e "efm-langserver installed."
fi

# check for diagnostic-languageserver
if [[ ! $(command -v "diagnostic-languageserver") ]]; then
  echo -e "diagnostic-languageserver not installed. run: npm i -g diagnostic-languageserver"
else
  echo -e "diagnostic-languageserver installed."
fi

# check for tmux plugin manager (tpm)
if [[ ! -f ~/.tmux/plugins/tpm/README.md ]]; then
  echo -e "tmux plugin manager not installed. go to https://github.com/tmux-plugins/tpm"
else
  echo -e "tmux plugin manager installed."
fi

# check for zsh
if [[ ! $(command -v "zsh") ]]; then
  echo -e "zsh not installed. wut."
else
  echo -e "zsh installed."
fi

# check for antidote
if [[ ! -f "$(brew --prefix)/opt/antidote/share/antidote/antidote.zsh" ]]; then
  echo -e "antidote not installed. run: brew install antidote"
else
  echo -e "antidote installed."
fi

# check that the antidote plugins have been bundled.
if [[ ! -f ~/.zsh_plugins.zsh ]]; then
  echo -e "antidote plugins not bundled. run: antidote bundle <~/.zsh_plugins.txt >~/.zsh_plugins.zsh"
else
  echo -e "antidote plugins bundled."
fi

# check for sketchybar
if [[ ! $(command -v "sketchybar") ]]; then
  echo -e "sketchybar not installed. run: brew tap FelixKratz/formulae && brew install sketchybar && brew services start sketchybar"
else
  echo -e "sketchybar installed."
fi

# check for yabai
if [[ ! $(command -v "yabai") ]]; then
  echo -e "yabai not installed. run: brew install koekeishiya/formulae/yabai"
else
  echo -e "yabai installed."
fi

# check for skhd
if [[ ! $(command -v "skhd") ]]; then
  echo -e "skhd not installed. run: brew install koekeishiya/formulae/skhd"
else
  echo -e "skhd installed."
fi

# check for borders
if [[ ! $(command -v "borders") ]]; then
  echo -e "borders not installed. run: brew install brew install FelixKratz/formulae/borders"
else
  echo -e "borders installed."
fi

# check for gnu-sed
if [[ ! $(command -v "gsed") ]]; then
  echo -e "gnu-sed not installed. run: brew install gnu-sed"
else
  echo -e "gnu-sed installed."
fi
