#!/bin/bash

# This script is used to check if a new computer has all the desired programs
# installed, if not it helps instruct how to install them.

# check for brew
if [[ ! $(command -v "brew") ]]; then
  echo -e "brew not installed. go to https://brew.sh/"
else
  echo -e "brew installed."
fi

# check for stow
if [[ ! $(command -v "stow") ]]; then
  echo -e "stow not installed. run brew install stow"
else
  echo -e "stow installed."
fi

# check for fast node manager (fnm)
if [[ ! $(command -v "fnm") ]]; then
  echo -e "fnm not installed. run brew install fnm"
else
  echo -e "fnm installed."
fi
# check for node (and npm)
if [[ ! $(command -v "node") ]]; then
  echo -e "node not installed. run fnm install <VERSION>"
else
  echo -e "node installed."
fi

# check for neovim
if [[ ! $(command -v "nvim") ]]; then
  echo -e "neovim not installed. run brew install neovim"
else
  echo -e "neovim installed."
fi

# check for tmux
if [[ ! $(command -v "tmux") ]]; then
  echo -e "tmux not installed. run: brew install tmux"
else
  echo -e "tmux installed."
fi

# check for tmux plugin manager (tpm)
if [[ ! -f ~/.tmux/plugins/tpm/README.md ]]; then
  echo -e "tmux plugin manager not installed. go to https://github.com/tmux-plugins/tpm"
else
  echo -e "tmux plugin manager installed."
fi

# check for zsh
if [[ ! $(command -v "zsh") ]]; then
  echo -e "zsh not installed. wut."
else
  echo -e "zsh installed."
fi

# check for antidote
if [[ ! -f "$(brew --prefix)/opt/antidote/share/antidote/antidote.zsh" ]]; then
  echo -e "antidote not installed. run: brew install antidote"
else
  echo -e "antidote installed."
fi

# check that the antidote plugins have been bundled.
if [[ ! -f ~/.zsh_plugins.zsh ]]; then
  echo -e "antidote plugins not bundled. run: antidote bundle <~/.zsh_plugins.txt >~/.zsh_plugins.zsh"
else
  echo -e "antidote plugins bundled."
fi
