#!/bin/bash

stow --target=$HOME alacritty
stow --target=$HOME fzf
stow --target=$HOME nvim
stow --target=$HOME sketchybar
stow --target=$HOME tmux
stow --target=$HOME wezterm
stow --target=$HOME yabai
stow --target=$HOME zsh
