#!/bin/bash

# This script is currently a work-in-progress and has not yet been tested.

# install brew if its not already available
if [[ ! $(command -v "brew") ]]; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# install stow via brew if its not already available
if [[ ! $(command -v "stow") ]]; then
  brew install stow
fi

# install eza via brew if its not already available
if [[ ! $(command -v "eza") ]]; then
  brew install eza
fi

# install zoxide via brew if its not already available
if [[ ! $(command -v "zoxide") ]]; then
  brew install zoxide
fi

# install fd via brew if its not already available
if [[ ! $(command -v "fd") ]]; then
  brew install fd
fi

# install rg via brew if its not already available
if [[ ! $(command -v "rg") ]]; then
  brew install ripgrep
fi

# install fzf via brew if its not already available
if [[ ! $(command -v "fzf") ]]; then
  brew install fzf
fi

# install fnm via brew if its not already available
if [[ ! $(command -v "fnm") ]]; then
  brew install fnm
fi

if [[ ! $(command -v "nvim") ]]; then
  brew install neovim
fi

if [[ ! $(command -v "tmux") ]]; then
  brew install tmux
fi

# check for tmux plugin manager (tpm)
if [[ ! -f ~/.tmux/plugins/tpm/README.md ]]; then
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

if [[ ! $(command -v "wezterm") ]]; then
  brew install --cask wez/wezterm/wezterm
fi

if [[ ! $(command -v "node") ]]; then
  fnm install v16.19.0
fi

if [[ ! $(command -v "sketchybar") ]]; then
  # @todo: download and install SF symbols pkg: https://developer.apple.com/sf-symbols/
  # install the font
  brew tap homebrew/cask-fonts
  brew install --cask homebrew/cask-fonts/font-hasklug-nerd-font
  # install sketchybar
  brew install FelixKratz/formulae/sketchybar
  # run automatically at startup
  brew services start sketchybar
fi

if [[ ! $(command -v "yabai") ]]; then
  brew install koekeishiya/formulae/yabai
  yabai --start-service
fi

if [[ ! $(command -v "skhd") ]]; then
  brew install koekeishiya/formulae/skhd
  skhd --start-service
fi

if [[ ! $(command -v "borders") ]]; then
  # install borders
  brew install FelixKratz/formulae/borders
  # run automatically at startup
  brew services start borders
fi

if [[ ! $(command -v "gsed") ]]; then
  brew install gnu-sed
fi

if [[ ! -d /Applications/Raycast.app ]]; then
  brew install --cask raycast
fi

echo -e "Setup complete. Now run ./install to apply the config"
