# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

command_timeout = 2000

[shlvl]
disabled = true
[singularity]
disabled = true
[kubernetes]
disabled = true
[vcsh]
disabled = true
[hg_branch]
disabled = true
[docker_context]
disabled = true
[package]
disabled = true
[c]
disabled = true
[cmake]
disabled = true
[cobol]
disabled = true
[daml]
disabled = true
[dart]
disabled = true
[deno]
disabled = true
[dotnet]
disabled = true
[elixir]
disabled = true
[elm]
disabled = true
[erlang]
disabled = true
[golang]
disabled = true
[haskell]
disabled = true
[helm]
disabled = true
[java]
disabled = true
[julia]
disabled = true
[kotlin]
disabled = true
[lua]
disabled = true
[nim]
disabled = true
[nodejs]
disabled = true
[ocaml]
disabled = true
[perl]
disabled = true
[php]
disabled = true
[pulumi]
disabled = true
[purescript]
disabled = true
[python]
disabled = true
[raku]
disabled = true
[rlang]
disabled = true
[red]
disabled = true
[ruby]
disabled = true
[rust]
disabled = true
[scala]
disabled = true
[swift]
disabled = true
[terraform]
disabled = true
[vlang]
disabled = true
[vagrant]
disabled = true
[zig]
disabled = true
[buf]
disabled = true
[nix_shell]
disabled = true
[conda]
disabled = true
[meson]
disabled = true
[spack]
disabled = true
[memory_usage]
disabled = true
[aws]
disabled = true
[gcloud]
disabled = true
[openstack]
disabled = true
[azure]
disabled = true
[env_var]
disabled = true
[crystal]
disabled = true
#[custom]
#disabled = true
[sudo]
disabled = true
[line_break]
disabled = true
[jobs]
disabled = true
[battery]
disabled = true
[time]
disabled = true
[status]
disabled = true
[container]
disabled = true
[shell]
disabled = true
