#!/bin/bash

if [[ ! $(command -v "brew") ]]; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# install stow via brew if its not already available
if [[ ! $(command -v "stow") ]]; then
  brew install stow
fi

# install eza via brew if its not already available
if [[ ! $(command -v "eza") ]]; then
  brew install eza
fi

# install zoxide via brew if its not already available
if [[ ! $(command -v "zoxide") ]]; then
  brew install zoxide
fi

# install fd via brew if its not already available
if [[ ! $(command -v "fd") ]]; then
  brew install fd
fi

# install rg via brew if its not already available
if [[ ! $(command -v "rg") ]]; then
  brew install ripgrep
fi

# install fzf via brew if its not already available
if [[ ! $(command -v "fzf") ]]; then
  brew install fzf
fi

# install fnm via brew if its not already available
if [[ ! $(command -v "fnm") ]]; then
  brew install fnm
fi

if [[ ! $(command -v "nvim") ]]; then
  brew install neovim
fi

if [[ ! $(command -v "tmux") ]]; then
  brew install tmux
fi

# check for tmux plugin manager (tpm)
if [[ ! -f ~/.tmux/plugins/tpm/README.md ]]; then
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

if [[ ! $(command -v "wezterm") ]]; then
  brew install --cask wez/wezterm/wezterm
fi

if [[ ! $(command -v "node") ]]; then
  fnm install v16.19.0
fi

if [[ ! $(command -v "sketchybar") ]]; then
  # @todo: download and install SF symbols pkg: https://developer.apple.com/sf-symbols/
  # install the font
  brew tap homebrew/cask-fonts
  brew install --cask homebrew/cask-fonts/font-hasklug-nerd-font
  # install sketchybar
  brew install FelixKratz/formulae/sketchybar
  # run automatically at startup
  brew services start sketchybar
fi

if [[ ! $(command -v "aerospace") ]]; then
  brew install --cask nikitabobko/tap/aerospace
fi

if [[ ! $(command -v "borders") ]]; then
  # install borders
  brew install FelixKratz/formulae/borders
  # run automatically at startup
  brew services start borders
fi

if [[ ! $(command -v "gsed") ]]; then
  brew install gnu-sed
fi

if [[ ! -d /Applications/Raycast.app ]]; then
  brew install --cask raycast
fi

if [ ! -d "$HOME/.antidote" ]; then
  git clone --depth=1 https://github.com/mattmc3/antidote.git ${HOME}/.antidote
fi

# install oh-my-posh
curl -s https://ohmyposh.dev/install.sh | bash -s

# add git aliases
git config --global alias.ci "commit"
git config --global alias.co "checkout"
git config --global alias.br "branch"
git config --global alias.st "status"
git config --global core.editor "nvim"
