#!/bin/bash

mkdir -p $HOME/local-tools

# install stow if its not already available
if [[ ! $(command -v "stow") ]]; then
  apt install -y stow
fi

# install eza if its not already available
if [[ ! $(command -v "eza") ]]; then
  cd $HOME/local-tools
  wget -c https://github.com/eza-community/eza/releases/latest/download/eza_x86_64-unknown-linux-gnu.tar.gz -O - | tar xz
  ln -s $HOME/local-tools/eza $HOME/.local/bin/eza
  cd $HOME/local-tools
fi

# install zoxide if its not already available
if [[ ! $(command -v "zoxide") ]]; then
  cd $HOME/local-tools
  mkdir zoxide
  cd zoxide
  wget -c https://github.com/ajeetdsouza/zoxide/releases/download/v0.9.6/zoxide-0.9.6-x86_64-unknown-linux-musl.tar.gz -O - | tar xz
  ln -s $HOME/local-tools/zoxide $HOME/.local/bin/zoxide
  cd $HOME/local-tools
fi

# install fd if its not already available
if [[ ! $(command -v "fd") ]]; then
  cd $HOME/local-tools
  wget -c https://github.com/sharkdp/fd/releases/download/v10.2.0/fd-v10.2.0-x86_64-unknown-linux-musl.tar.gz -O - | tar xz
  ln -s $HOME/local-tools/fd-v10.2.0-x86_64-unknown-linux-musl/fd $HOME/.local/bin/fd
  cd $HOME/local-tools
fi

# install rg if its not already available
if [[ ! $(command -v "rg") ]]; then
  cd $HOME/local-tools
  wget -c https://github.com/BurntSushi/ripgrep/releases/download/14.1.1/ripgrep-14.1.1-x86_64-unknown-linux-musl.tar.gz -O - | tar xz
  ln -s $HOME/local-tools/ripgrep-14.1.1-x86_64-unknown-linux-musl/rg $HOME/.local/bin/rg
  cd $HOME/local-tools
fi

# install fzf if its not already available
if [[ ! $(command -v "fzf") ]]; then
  cd $HOME/local-tools
  wget -c https://github.com/junegunn/fzf/releases/download/v0.55.0/fzf-0.55.0-linux_amd64.tar.gz -O - | tar xz
  ln -s $HOME/local-tools/fzf $HOME/.local/bin/fzf
  cd $HOME/local-tools
fi

if [[ ! $(command -v "nvim") ]]; then
  cd $HOME/local-tools
  wget -O nvim-linux64.tar.gz https://github.com/neovim/neovim/releases/download/v0.10.2/nvim-linux64.tar.gz
  tar xzvf nvim-linux64.tar.gz
  ln -s $HOME/local-tools/nvim-linux64/bin/nvim $HOME/.local/bin/nvim
  cd $HOME/local-tools
fi

# if [[ ! $(command -v "tmux") ]]; then
#
# fi

# check for tmux plugin manager (tpm)
# if [[ ! -f ~/.tmux/plugins/tpm/README.md ]]; then
#   git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
# fi

# if [[ ! $(command -v "gsed") ]]; then
#
# fi


# install oh-my-posh
curl -s https://ohmyposh.dev/install.sh | bash -s
